### ISSUE TITLE
rakuten.co.jp

### ISSUE THREAD

**Issue by LordBadmintonofYorkshire** [k2jp/abp-japanese-filters#1]
When visiting rakuten.co.jp a pop-up overlay element appears asking if the visitor is sure he / she doesn't want to visit the international rakuten.com instead, even though the visitor was probably aware that a site with a Japanese TLD will most likely be Japanese and would have gone to the English .com site directly if that was the visitor's intention. Can you add that annoying pop-up element to the filter?

rakuten.co.jp###dipPopUpBoxMask

**Comment by k2jp** [comment]
- Send issue report with minimum enabled subscription if possible.
- "abp_jp.txt" does not include element-hiding filters at all, but "abp_jp_element_hiding.txt" does. Do you mean you want me to add your filter above to "abp_jp.txt"?

**Comment by LordBadmintonofYorkshire** [comment]
What subscriptions would that be? EasyList, ABP Japanese filters and maybe Fanboy's Annoyance List?
Add it to abp_jp_element_hiding.txt.

**Comment by k2jp** [comment]
> Add it to abp_jp_element_hiding.txt.

It could be possible.

One more thing for me to confirm, I fail to reproduce the problem even with fake IP outside Japan. That's why I said "Send issue report". The report would be helpful for me to reproduce.

**Comment by LordBadmintonofYorkshire** [comment]
Ok, I'll submit it at some point when I have time. Could it be that the website sees that your OS' language is Japanese?

**Comment by k2jp** [comment]
Expired

**Comment by LordBadmintonofYorkshire** [comment]
Sorry, I completely forgot about this. Here is the issue report (better late than never): https://reports.adblockplus.org/7d3f8cdf-2bc6-46bc-88c5-242d9cb04e34#tab=requests

**Comment by k2jp** [comment]
The filter you looking for would be the following...

rakuten.co.jp##[id^="dipPopUpBox"]

or

www.rakuten.co.jp##[id^="dipPopUpBox"]

But, won't be added to the ABP Element-hiding subscription because your request is too special. I guess some users like to see the warning.

**Comment by LordBadmintonofYorkshire** [comment]
I know about the filter myself and just wanted to submit it. The creator of Fanboy's Annoyance List told me to submit it here since he saw it more as an ad than an annoyance (I personally think it's the other way around): https://forums.lanik.us/viewtopic.php?f=62&t=19707

When a visitor goes to a site with a Japanese TLD they are most likely aware that the site is probably going to be in Japanese. If they wanted to go to the international version then they would probably have gone to the .com TLD in the first place.

**Comment by k2jp** [comment]
- Basically, ABP Japanese Filters are only for Japanese people/region.
  - Detail for [support policy](https://code.google.com/p/adblock-plus-japanese-filter/wiki/Support_Policy)
- The element-higing filter I wrote above could hide other messages which should not be hidden.

These are reasons why I do not add the filter to the subscription.

**Comment by LordBadmintonofYorkshire** [comment]
Ok.
