### ISSUE TITLE
Revert imgur rule

### ISSUE THREAD

**Issue by duckness** [k2jp/abp-japanese-filters#12]
Patch 94591cc. Vulnerability in imgur patched. See: http://imgur.com/blog/2015/09/22/imgur-vulnerability-patched/

Currently it blocks any site trying to embed imgur.com images.

**Comment by k2jp** [comment]
- Read [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy).
- imgur.com is also used for (animated) AD banners. That's why third-party migur.com is still blocked.

> Currently it blocks any site trying to embed imgur.com images.
- If you have problems, leave example URLs or send Issue Report via Adblock Plus for Firefox.

**Comment by ghost** [comment]
you can add a whitelist rule for it in your own filters:

```
@@||imgur.com^$third-party
```

**Comment by k2jp** [comment]
Expired
