### ISSUE TITLE
[False-positive] facebook.com - broken game My Little Monsters

### ISSUE THREAD

**Issue by Alex-302** [k2jp/abp-japanese-filters#15]
rule

```
/ping.*?$image,object,subdocument
```

solution

```
@@||facebook.com/connect/ping$domain=starislandgames.net
```

**Comment by k2jp** [comment]
[Wrong subscription] No support available for you
- You are violating the [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy).
- Use [other appropriate subscription](https://adblockplus.org/en/subscriptions).

**Comment by Alex-302** [comment]
Screenshot
http://imagizer.imageshack.com/img923/2506/W3LHDz.jpg
URL
https://apps.facebook.com/my-little-monsters/?fb_source=search&ref=ts&fref=ts
Why don't you can just add that exclusion?

**Comment by k2jp** [comment]
Because users like you don't respect the [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy).

**Comment by Alex-302** [comment]
```
facebook.com <- I don't have its account.
```

Because this?
