### ISSUE TITLE
Filter blocks access to Hummingbird.me

### ISSUE THREAD

**Issue by wopian** [k2jp/abp-japanese-filters#16]
Attempting to access [Hummingbird](https://hummingbird.me), an anime and manga tacking site, triggers the `/hummingbird.` filter that was added in a commit before the migration from Google Code. Happens with both ABP and uBlock.

Offending line: [abpjf.txt#L2296](https://github.com/k2jp/abp-japanese-filters/blob/25a9bda0001cd169b75ccd6596806ec8c38ae650/abpjf.txt#L2296)

Accessing `https://hummingbird.me` results in:
![](http://i.imgur.com/KptSI3n.png)

Instead of loading the site:
![](http://i.imgur.com/ObjlZBW.jpg)

**Comment by k2jp** [comment]
Read the [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy) before reporting.

https://github.com/k2jp/abp-japanese-filters/commit/01f2b200e2ad74637c6ef22390fef0cc467aaf40

**Comment by wopian** [comment]
> Read the Support Policy before reporting.

I did before opening this issue.
