### ISSUE TITLE
Nyaa.se fix

### ISSUE THREAD

**Issue by Catarax** [k2jp/abp-japanese-filters#17]
||files.nyaa.eu/ba_.$image
||files.nyaa.se/ba_.$image

Update the filter like this filter in order to block the ads-banner.

**Comment by k2jp** [comment]
Thank you for reporting.
- The problem should be fixed like... https://github.com/k2jp/abp-japanese-filters/commit/f42f27e293aea2a0baa7cd71c1ce0d0f4598d059
- Remember the [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy)
