### ISSUE TITLE
Nyaa.se update

### ISSUE THREAD

**Issue by Catarax** [k2jp/abp-japanese-filters#18]
Need to add :
||files.nyaa.eu/bb_.$image
||files.nyaa.se/bb_.$image

**Comment by k2jp** [comment]
[Warning]
In the [previous issue](https://github.com/k2jp/abp-japanese-filters/issues/17) you submitted, I replied that **Remember the [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy)**.
Do you **understand** that?

**Comment by Catarax** [comment]
Ok I understand that, will not help you anymore since i'm not japanese by the way.
Support Policy is the future.
