### ISSUE TITLE
False Positive → Toyota Recall Site

### ISSUE THREAD

**Issue by TPS** [k2jp/abp-japanese-filters#19]
Neither http://touch.Toyota.com/recall nor http://WWW.Toyota.com/recall function w/o whitelisting `touch.Toyota.com` & `Toyota.com`, respectively.  When doing so, no ads appear, anyway, so maybe these 2 sites should be whitelisted outright.

Maybe the CAPTCHA is fouling this?

Replicating from https://github.com/AdguardTeam/AdguardFilters/issues/2224

**Comment by k2jp** [comment]
Expired (Adguard no longer includes ABP Japanese Filters)
