### ISSUE TITLE
geekkeys.com

### ISSUE THREAD

**Issue by tp7** [k2jp/abp-japanese-filters#2]
Geekkeys.com gets most of its requests blocked with this filter list enabled in either AdBlock or uBlock, ending up completely broken.

**Comment by k2jp** [comment]
[ Support policy violation = Won't Fix! ]
https://code.google.com/p/adblock-plus-japanese-filter/wiki/Support_Policy

**Comment by tp7** [comment]
If you need a screenshot then here's one from [this page](http://www.geekkeys.com/holyoops-eva-aluminum-keycap/) but you should be able to reproduce the issue on any page on that domain.
![http://www.geekkeys.com/holyoops-eva-aluminum-keycap/](https://pbs.twimg.com/media/B6aY6JyCMAAhTyM.png:large)
Or is there some other non-racist policy that I'm violating here?

**Comment by k2jp** [comment]
Support cost/time/"mother tongue"...
These are the reasons to limit people/region to support.
You should select appropriate subscription and expect that.
