### ISSUE TITLE
False positive on http://www.mcdonalds.com.hk/ch/24-hours-mcdelivery.html

### ISSUE THREAD

**Issue by DummySYSTEM** [k2jp/abp-japanese-filters#22]
False positive on http://www.mcdonalds.com.hk/ch/24-hours-mcdelivery.html , image which have "promotion" in url are being blocked.
eg: http://www.mcdonalds.com.hk/content/dam/hongkong/English/24_hours_mcdelivery/promotion/tropicavo-chicken-burger.png

http://www.mcdonalds.com.hk/content/dam/hongkong/English/24_hours_mcdelivery/promotion/ebi-burger-with-pineapple.png

**Comment by k2jp** [comment]
### Who says ABP Japanese Filters have global support?
- https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy

**Comment by DummySYSTEM** [comment]
Sorry  may be I didn't read the policy very well  but I currently live in Japan and just want to report a false positive which I encountered at work. I will close the case and sorry about the disturbing.
