### ISSUE TITLE
Thumbnails on NicoNico ranking are not displayed

### ISSUE THREAD

**Issue by Mach-555** [k2jp/abp-japanese-filters#23]
I use uBlock Origin on firefox 48 on windows.
When I visit niconico videos (http://www.nicovideo.jp/ranking),
video's thumbnails under 21 on video ranking are not displayed.
![before](https://cloud.githubusercontent.com/assets/14326171/17642641/96a70694-6188-11e6-8ed1-d6ac3c84fe89.jpg)

I annuled  ABP Japanese filters  by way of trial, then the thunbnails were displayed normally.
![after](https://cloud.githubusercontent.com/assets/14326171/17642645/a4452c0e-6188-11e6-8408-5c3fec491cd1.jpg)

**Comment by k2jp** [comment]
- Install Adblock Plus and send Issue Report via right-clicking on the Adblock Plus icon.
- Don't expect me to reproduce the problem because there would be fake or trap reports.

**Comment by k2jp** [comment]
Expired
