### ISSUE TITLE
Breaks Google Play Music

### ISSUE THREAD

**Issue by yshui** [k2jp/abp-japanese-filters#25]
Rule `https:*?*&ip=$third-party` blocks Google Play Music

**Comment by k2jp** [comment]
Thank you for reporting.

Send Issue Report via Adblock Plus addon for Firefox, by right-clicking on the Adblock Plus icon, to confirm the problem.

The whitelist filter will be similar to YouTube one.
@@||googlevideo.com^_?_&ip=$domain=youtube.com

**Comment by k2jp** [comment]
Expired
