### ISSUE TITLE
 aliexpress incorrect blocking

### ISSUE THREAD

**Issue by IRainman** [k2jp/abp-japanese-filters#28]
The full website blocking is not necessary.

||aliexpress.com^

Suffice it to block

||click.aliexpress.com^

**Comment by k2jp** [comment]
#### Facts
- aliexpress.com was reported quite offen via Adblock Plus Issue Report form users as destination of **forced** AD landing pages.
- aliexpress.com used subdomains for the AD landing pages like click.aliexpress.com , offer.aliexpress.com and more. I gave up to add subdomains each time.
##### Don't forget Support Policy
- https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy


Enough reasons to block the whole domain.

**Comment by IRainman** [comment]
OK. I deleted your filter from my blocker. Thank you for the quick response.
