### ISSUE TITLE
Google Analytics works by full site whitelisting

### ISSUE THREAD

**Issue by tp7** [k2jp/abp-japanese-filters#3]
Right now GA works only because the entire site is whitelisted in the filter list, which is kinda bad because the user loses the ability to block any desired elements on the page. It also doesn't work with extensions that don't allow full site whitelisting in the rules set, like uBlock (twitter discussion [here](https://twitter.com/tp7ptr/status/551500104428187648)).

Refactoring the list to avoid using full site whitelisting would be very nice.

**Comment by k2jp** [comment]
Send Issue Report if you use Adblock Plus for Firefox.

**Comment by tp7** [comment]
I'm not sure why you even have issues tracking enabled in this repo if you aren't going to accept them.
