### ISSUE TITLE
ABP japanese filters breaks Folding@home web client

### ISSUE THREAD

**Issue by Nekoeko** [k2jp/abp-japanese-filters#30]
Folding@home (FAH) is a standalone program, intended for volunteers from any place in the world. It's separate from the browser, but the only way to see my progress and limit my processing power is [through a web client](http://folding.stanford.edu/client/). When I open that page, stanford.edu connects with my computer through the port 7396.

The web client doesn't work if I enable the ABP Japanese filter. It looks like I hadn't installed FAH in my computer, or I stopped FAH from the command line:

![Screenshot 1](https://cloud.githubusercontent.com/assets/24980882/21745581/7af76fc2-d52f-11e6-9288-e433a20aab8c.png)
![Screenshot 2](https://cloud.githubusercontent.com/assets/24980882/21745582/7afcc17a-d52f-11e6-96ba-1e535aafa069.png)

uBlock Origin reports that the filter

    ^ping^$third-party

blocks a script from

    http://127.0.0.1:7396/ping?callback=jQuery000000000000000000000_0000000000000&_=0000000000000

(with other numbers instead of zeros, they change every time I try to access the web client).
The most specific exceptions that allows the web client to work again is

    @@||127.0.0.1:7396/ping?callback=*^$script,domain=folding.stanford.edu

but maybe a more generic one would be better. Would a general whitelisting from 127.0.0.1 work, or is it horribly insecure and a horrible idea altogether?

I didn't try other distributed projects like SETI@home, it's possible they suffer a similar problem.

**Comment by mrsshr** [comment]
I have same issue here.
同じイシューを抱えています。

I'm using ublock origin extension on firefox and "Allow some non-intrusive advertising" option is disabled.
現在使っている　AdBlockerは　ublock　originであって　"Allow some non-intrusive advertising"　機能が非活性化しています。

フィルター　構文:
^ping$third-party
^ping.$third-party
影響を受けている　URL:
https://127.0.0.1:[port]/images/ping.png?[some_unixtime]

![image](https://cloud.githubusercontent.com/assets/4264612/22315589/fcfc03e6-e3aa-11e6-9eaf-b8f795e07456.png)
![image](https://cloud.githubusercontent.com/assets/4264612/22315575/ddf589f4-e3aa-11e6-92de-d0dbabf411f1.png)

**Comment by k2jp** [comment]
I'm sorry to respond too late.

https://github.com/k2jp/abp-japanese-filters/commit/a52ec3c48c512c7f62eddf2ebbe066f726f1cf15
