### ISSUE TITLE
"_campaign=$document" filters out too much innocent websites

### ISSUE THREAD

**Issue by dksher** [k2jp/abp-japanese-filters#31]
"_campaign=$document" was add to this filter recently. However, too many innocent websites use this phrase.

**Comment by k2jp** [comment]
#### Support Policy
- https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy

**Comment by nonamethanks** [comment]
@k2jp here's some examples from the top of my mind:

* The pixiv sketch button at the bottom of the screen redirects to the link `https://sketch.pixiv.net/?utm_source=pixiv&utm_medium=link&utm_content=toolmenu&utm_campaign=always`
* Deviantart uses the string "_campaign=$document" in the password recovery form email when linking to your own account (the url is in the form `http://accountname.deviantart.com/?utm_source=EMC&utm_medium=Communicator&utm_campaign=PDT_Account_ForgotUsername&utm_term=link`
* TorrentFreak RSS feed links have the format `https://torrentfreak.com/ahashare-disappears-after-domain-name-suspension-170131/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Torrentfreak+(Torrentfreak)`
* Gitter uses this format for badge links in github repositories: `https://gitter.im/<your repository>?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge`

There's more, much more innocent results, these are simply the ones that happened to me most recently. This rule constantly throws out errors for sites that are completely fine, to the point where it's necessary to edit it out or disable the whole filter list half the time.

**Comment by k2jp** [comment]
@nonamethanks 
- First of all, remember the name of the subscription: 
  - ABP Japanese filters (ONLY FOR __Japanese__ and __experienced__ users: READ [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy))
- I know some web sites use _campaign= in the URL.
  - [OFF THE TOPIC] Your example URLs include utm_&lowast;. UTM means __Urchin Tracking Module__.
- More serious problem is that [some malicious redirected landing pages](http://k2jp.hatenablog.com/) also use _campaign. These must be blocked.
- If you are __experienced__ user, you should know how to write a exceptional filter as white list.
- If you are __experienced__ user, you should know how to eliminate useless ?&lowast;= and &&lowast;= used for tracking and tagging.
- If not... sad news, you have to remember the name of the subscription again.

**Comment by WhiteCat6142** [comment]
it blocks innocuous websites such as Mozilla newsletter more than harmful ones.
i know that it means tracking,but it is too strict for normal browsing.
furthermore,blocking them cannot be a solution of tracking.
百害あって一理なし

**Comment by k2jp** [comment]
- https://github.com/k2jp/abp-japanese-filters/commit/1da7e0f78f4925469ef29fe6d78b69e36016ba33
The commit message says **Block AD redirection with uBlock Origin**, based on [weekly issue reports](http://k2jp.hatenablog.com/)
I didn't say that the filter was used for tracking...

- https://github.com/gorhill/uBlock/wiki/Strict-blocking
You can **Disabling strict blocking for** DOMAIN (**Temporarily** / **Permanently**).

**Comment by WhiteCat6142** [comment]
anyway,it should be more specific.
I already disabled strict blocking for about 10 domains.I have had it.

**Comment by k2jp** [comment]
#### I don't think "it should be more specific"
- It takes too much time for me to maintain **more specific** filters.
- FYI: EasyList family has **more specific** filters.

#### Before you ask me
- Just try/test/evaluate your idea for yourself.

#### If you dislike false positives, find better subscriptions, or fork it(, and optionally PR me).
- https://filterlists.com/
- https://adblockplus.org/en/subscriptions
