### ISSUE TITLE
NSFW hjav5278.com

### ISSUE THREAD

**Issue by ericliujian** [k2jp/abp-japanese-filters#33]
|http://$script,third-party,domain=hjav5278.com

**Comment by k2jp** [comment]
#### Name of the subscription
- ABP Japanese filters (ONLY FOR __Japanese__ and __experienced__ users: READ __Support Policy__ )

#### Support Policy
- https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy

**Comment by k2jp** [comment]
Expired
