### ISSUE TITLE
NSFW 

### ISSUE THREAD

**Issue by ericliujian** [k2jp/abp-japanese-filters#34]
Could you remove pornhub.com from the blocked part? I can watch

**Comment by ericliujian** [comment]
also please remove porn.com

**Comment by k2jp** [comment]
#### Name of the subscription
- ABP Japanese filters (ONLY FOR __Japanese__ and __experienced__ users: READ __Support Policy__ )

#### Support Policy
- https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy
