### ISSUE TITLE
Yahoo.co.jp boken captcha

### ISSUE THREAD

**Issue by ghgh2231aacc300lol** [k2jp/abp-japanese-filters#37]
![tmp_26962-img_20170412_0432242014035071](https://cloud.githubusercontent.com/assets/27303994/24927257/65a387ec-1f39-11e7-82a2-7cc1cda0447d.png)

https://mail.yahoo.co.jp/ (I cannot provide an exact link because the registration link seems to be dynamic)

Having abp-japanese-filters makes it very likely for the yahoo.co.jp captcha to fail when making a new account, even if the characters are correct. It can take 2-10 tries with the filter enabled. It always takes me 1 try with the filter disabled. Reproduced on Firefox ESR (Windows 7), Firefox 51&52 (fedora), and Firefox 52.02 (Android7), all using ublock origin.

**Comment by k2jp** [comment]
1. Install Adblock Plus to make use of Issue Reporting feature
1. Send an Issue Report by the Adblock Plus
1. URL is provided for the report
1. Paste the URL here
"**It can take 2-10 tries with the filter enabled**" sounds odd to me.
I have never heard a wrong filter increase the repeating CAPTCHA input.

#### Support Policy
- https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy

**Comment by k2jp** [comment]
Expired
