### ISSUE TITLE
It blocks all the domains of the Principality of Andorra (.ad)

### ISSUE THREAD

**Issue by T-K-Y-M** [k2jp/abp-japanese-filters#38]
I've noticed there is one rule in this filter that blocks all the webpages of the  [(.ad) domain](https://en.wikipedia.org/wiki/.ad) blocking an entire country.

The rule is this: 
> **http:*.ad^**

Some webpages from there to test: www.govern.ad (Government) www.elperiodic.ad (Newspaper) 

I don't know if there is an easy way to by-pass that keeping the feature to block subdomains with .ad in them but without blocking the main domain (.ad). 

Just wanted to report this unexpected behavior of the filter and thank you for the work you do developing and maintaining this project.

**Comment by k2jp** [comment]
Thank you for reporting @Rockbdn .
The problem will be fixed with the following commit.
https://github.com/k2jp/abp-japanese-filters/commit/8798824de861504afe87fc1a3a305927bd6338c8
