### ISSUE TITLE
Disqus comments on torrentfreak.com blocked

### ISSUE THREAD

**Issue by anonsubmitter** [k2jp/abp-japanese-filters#4]
abp-japanese-filters blocks Disqus comments in articles on http://torrentfreak.com/ from loading.

**Comment by k2jp** [comment]
See Support Policy: https://code.google.com/p/adblock-plus-japanese-filter/wiki/Support_Policy

**Comment by anonsubmitter** [comment]
Is this report invalid because I didn't provide an exact URL or because it's a non-Japanese site?

**Comment by k2jp** [comment]
See: https://github.com/k2jp/abp-japanese-filters/issues/2#issuecomment-68632820
