### ISSUE TITLE
ajax.cloudflare.com

### ISSUE THREAD

**Issue by mverrilli** [k2jp/abp-japanese-filters#40]
I don't think this is appropriate. It breaks a lot of websites that use cloudflare.  Cloudflare will inject scripts automatically to do things like email obfuscation.

**Comment by k2jp** [comment]
I'm sorry to respond too late.

Do you offer some example web pages to reproduce?
You can send Issue Report via Adblock Plus. (Leave comment and its URL)

Remember to check [Issue Report](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy).

**Comment by mverrilli** [comment]
Examples: 
https://ajax.cloudflare.com/cdn-cgi/scripts/2448a7bd/cloudflare-static/rocket-loader.min.js
https://ajax.cloudflare.com/cdn-cgi/scripts/2448a7bd/cloudflare-static/email-decode.min.js

I'm sure there are more. I'm not sure I understand blocking this entire subdomain at all. Are there actually ads run from there? This is a cloud service that provides HA and reverse web proxies for many websites and has lots of features that break if you ban the entire ajax subdomain.

**Comment by k2jp** [comment]
Thank you for the examples. They seem harmless.

Background info: `||ajax.cloudflare.com^` was added to block third-party scripts used for analytics, March 27, 2013.

Now that the filter looks too ambitious, it is commented out for the time being.
* https://github.com/k2jp/abp-japanese-filters/commit/305a2e0cb27544280b99349798f5fe0f553e7a4b

Thank @mverrilli for your help.

**Comment by yessgalal** [comment]
Free CDN Free | Speed your website | Increasing the speed with which your website load times, Reducing bandwidth costs https://www.freecdncloud.com/ <a href="https://www.freecdncloud.com">Free CDN</a>
