### ISSUE TITLE
False positives for "-conduit-"

### ISSUE THREAD

**Issue by mt-caret** [k2jp/abp-japanese-filters#41]
Haskell, a programming language, has a concept called a "conduit", for streaming data.
URLs with "conduit" in it triggers the rule and caused hard-to-identify breakage.
ex. https://hackage.haskell.org/package/twitter-conduit-0.2.2.2/docs/Web-Twitter-Conduit.html

**Comment by k2jp** [comment]
I'm sorry to respond too late.

@@-conduit-$domain=haskell.org

Test the filter above and tell me whether it works please.

Remember to check [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy).

**Comment by mt-caret** [comment]
I no longer use this filter, so I can't test this; feel free to close. Thanks!
