### ISSUE TITLE
generic 'ads' filter is too broad

### ISSUE THREAD

**Issue by jacklinzoho** [k2jp/abp-japanese-filters#42]
-ads^ and similar filters are way too broad.  For example, it blocks any searches of the word 'ads', and any pages that talk about ads.

This filter needs to be removed altogether rather than whitelisting case-by-case.

**Comment by k2jp** [comment]
I'm sorry to respond too late.

It's your opinion, not mine.
You can create your own filter or subscription.
You can use EasyList or other subscription
* https://adblockplus.org/en/subscriptions
* https://filterlists.com/
