### ISSUE TITLE
"_promoted^" inadvertently catches Twitter's “Report User”

### ISSUE THREAD

**Issue by liyang** [k2jp/abp-japanese-filters#43]
… while attempting to report a spam account that started retweeting my tweets.

The exact URL accessed was:

```
https://twitter.com/i/safety/report_story?client_location=profile%3Aprofile%3Aprofile_follow_card&client_referer=%2Fi%2Fnotifications&is_media=false&is_promoted=false&lang=en&next_view=report_story_start&profile_id=867168690386735100&reported_user_id=867168690386735104&reporter_user_id=19751424&source=reportprofile
```

I'm not sure what kind of URLs the original filter was attempting to block. I ended up adding this to my filters:
```
@@||twitter.com/i/safety/
```

**Comment by k2jp** [comment]
I'm sorry to respond too late.

https://github.com/k2jp/abp-japanese-filters/commit/5e95b97dab961ccdae068287092023d01ff5e729
