### ISSUE TITLE
NSFW f95zone.com

### ISSUE THREAD

**Issue by ltybcs** [k2jp/abp-japanese-filters#44]
Without Japan filter: https://image.prntscr.com/image/_YtEt_qyQVuG9Q7K85g-ZA.png
With Japan filter: https://image.prntscr.com/image/mvtdeuItQ3mMxPqXn4hJLg.png

**Comment by k2jp** [comment]
I'm sorry to respond too late.

Use Issue Report via Adblock Plus and leave comments and its URL.

Remember the [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy).
