### ISSUE TITLE
pornhub.com NSFW false positive

### ISSUE THREAD

**Issue by BlazDT** [k2jp/abp-japanese-filters#45]
https://www.pornhub.com/view_video.php?viewkey=ph5a39c2e3a4012

Site layout is broken if "ABP Japanese Filters" is active.

**Comment by BlazDT** [comment]
Not fixed yet, screenshot:

https://camo.githubusercontent.com/3b0f08fc99da30ed935d4130f9955a098d9b6360/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f677948345532502e706e67

**Comment by k2jp** [comment]
I'm sorry to respond too late.

I do not offer support for porn web sites.
Find and use other subscription...
* https://adblockplus.org/en/subscriptions
* https://filterlists.com/

Remember the [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy).
