### ISSUE TITLE
False Positive - Twitter Report Popup

### ISSUE THREAD

**Issue by elaine-jackson** [k2jp/abp-japanese-filters#46]
An exception may be needed to prevent the Japanese filters from blocking Twitter's report reasons popup.

**Screenshots:**
<img width="1280" alt="screen shot 2018-02-17 at 3 05 39 pm" src="https://user-images.githubusercontent.com/8227641/36345191-33a527e0-13f4-11e8-9f65-66821c5f4506.png">
<img width="1280" alt="screen shot 2018-02-17 at 3 08 15 pm" src="https://user-images.githubusercontent.com/8227641/36345205-6c0d9efa-13f4-11e8-8658-555b13cba771.png">
<img width="642" alt="screen shot 2018-02-17 at 3 06 14 pm" src="https://user-images.githubusercontent.com/8227641/36345192-33c6f6d6-13f4-11e8-93c6-bfe8d3867ac9.png">

**Comment by lae** [comment]
seems fixed
![image](https://user-images.githubusercontent.com/1318013/39669118-c3405494-5097-11e8-84a5-38aca64e1b74.png)
![image](https://user-images.githubusercontent.com/1318013/39669123-dee8a002-5097-11e8-8ff1-cb957058c44c.png)

**Comment by lae** [comment]
affects jpn twitter too
![image](https://user-images.githubusercontent.com/1318013/39669140-4200fba8-5098-11e8-987a-2d4add5cbfda.png)
(i forgot I temp disabled)

**Comment by k2jp** [comment]
I'm sorry to respond too late.

This report is useful and duplicated with https://github.com/k2jp/abp-japanese-filters/issues/43#issuecomment-464367722

Thank you nice screen shots which help a lot.
