### ISSUE TITLE
False positive in google search results

### ISSUE THREAD

**Issue by vozersky** [k2jp/abp-japanese-filters#49]
Trying to open techcrunch page from the search results
The new tab is closed by `|https:*-ad-$popup `

see the screenshot:

![image](https://user-images.githubusercontent.com/17472907/40797713-d5c01d32-6511-11e8-9e20-60e3dbd81f93.png)

**Comment by k2jp** [comment]
I'm sorry to respond too late.

You are joking.
You can just follow the link....

Remember the [Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy).
