### ISSUE TITLE
Breaks *-ad.

### ISSUE THREAD

**Issue by js-bar** [k2jp/abp-japanese-filters#50]
I can’t see the contents on [https://www.tri-ad.global](https://www.tri-ad.global) because of the filter that blocks **“https:*-ad.”**
It is the web site of an associated company of Toyota Motor Corporation.

Could you add “tri-ad.global” to the exception list?

**Comment by k2jp** [comment]
I'm sorry to respond too late.

Strange domain name...orz

https://github.com/k2jp/abp-japanese-filters/commit/d258035efe5785b13e2ca1a40708e9f824e6d1d2
