### ISSUE TITLE
 _campaign=$document breaks some links to https://www.pledgemusic.com 

### ISSUE THREAD

**Issue by gingerbeardman** [k2jp/abp-japanese-filters#54]
> uBlock Origin has prevented the following page from loading:
> https://www.pledgemusic.com/projects/spicule?utm_campaign=project13210&utm_medium=project_badge
> Because of the following filter
> _campaign=$document
> Found in: JPN: ABP Japanese filters (日本用フィルタ)

This block seems to have nothing specific to Japan?

**Comment by k2jp** [comment]
Sorry to respond too late.

ABP Japanese Filter is independent subscription.
In other words, it does not belong to EasyList family.

[Support Policy](https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy)

**Comment by gingerbeardman** [comment]
Correct. Your filter causes this issue.

**Comment by k2jp** [comment]
[Deplicated] https://github.com/k2jp/abp-japanese-filters/issues/31

**Comment by k2jp** [comment]
Typo...
[Duplicated] https://github.com/k2jp/abp-japanese-filters/issues/31

**Comment by k2jp** [comment]
[Duplicated] https://github.com/k2jp/abp-japanese-filters/issues/31
