### ISSUE TITLE
||jwpcdn.com^ 

### ISSUE THREAD

**Issue by ghost** [k2jp/abp-japanese-filters#58]
Rule breaks the music player on some sites.
https://github.com/k2jp/abp-japanese-filters/blob/831cedc78b5da6c105e035076a0dd2173df270dd/abp_jp.txt#L7380

http://mobilmp3tr.net/mobil-indir/vega-alisamadim-yokluguna

When enabled
<details><summary>Screenshot:</summary>

![mobilmp3tr net(1)](https://user-images.githubusercontent.com/34379403/72662862-16c8f800-39fd-11ea-8748-99e74a0d907b.png)

</details>

When disabled
<details><summary>Screenshot:</summary>

![mobilmp3tr net](https://user-images.githubusercontent.com/34379403/72662860-10d31700-39fd-11ea-8351-67bb45356049.png)

</details>

---

https://cbox.turkdown.com/index.php

When enabled

<details><summary>Screenshot:</summary>

![cbox turkdown com](https://user-images.githubusercontent.com/34379403/72662880-3c560180-39fd-11ea-850d-c5904979521e.png)

</details>

When disableb

<details><summary>Screenshot:</summary>

![cbox turkdown com(1)](https://user-images.githubusercontent.com/34379403/72662877-352ef380-39fd-11ea-96fc-ac9cf83839e3.png)

</details>

**Comment by krystian3w** [comment]
no support fix TR pages...

**Comment by krystian3w** [comment]
As I remember, the list no longer functions (available) in uBO and AdGuard as available from the list - who wants to have it on their own subscribed list or has to manually add it to AdGuard.
