### ISSUE TITLE
Filter breaks facebook. is_ad_preview: false getting caught by |https:*ad

### ISSUE THREAD

**Issue by Rimmer7** [k2jp/abp-japanese-filters#6]
![filterissue](https://cloud.githubusercontent.com/assets/11364702/6541744/fee40c38-c4e1-11e4-9942-91aa251181c7.jpg)
Feed functionality like editing your posts and such breaks as the context menu doesn't appear while using ABP Japanese Filters in μBlock.

My request log had this entry:
|https:*ad  xmlhttprequest  https://www.facebook.com/timeline/feed/options_menu/?button_id=u_0_1x&feed_context=%7B%22profile_id%22%3A100001274138338%2C%22story_width%22%3A513%2C%22fbfeed_context%22%3Atrue%2C%22location_type%22%3A10%2C%22is_starred%22%3Afalse%2C%22outer_object_element_id%22%3A%22tl_unit_-5152666325804765720%22%2C%22object_element_id%22%3A%22tl_unit_-5152666325804765720%22%2C%22is_ad_preview%22%3Afalse%2C%22is_editable%22%3Afalse%7D&story_token=S%3A_I100001274138338%3A937678836284579&hash_token=100001274138338%3A306061129499414%3A2%3A0%3A1427871599%3A-5152666325804765720

I notice that url string contains "is_ad_preview: false", and this particular line seems to be what the filter finds offensive.

I do want to use this list as I do surf Japanese sites.

**Comment by k2jp** [comment]
[Duplicated]
https://github.com/k2jp/abp-japanese-filters/issues/5#issuecomment-76384341
