### ISSUE TITLE
171 redundant rules found on abp japanese filters list.

### ISSUE THREAD

**Issue by smed79** [k2jp/abp-japanese-filters#9]
Hello, 
redundant found on abp japanese filters list:

`||by.analytics.yahoo.` has been made redundant by `.analytics.`
`||by.i.analytics.yahoo.` has been made redundant by `.analytics.`
`/google_analytics.` has been made redundant by `_analytics.`
`://analytics.$third-party` has been made redundant by `^analytics.`
`||tumblr.com/analytics.` has been made redundant by `^analytics.`
`^js^app^analytics^` has been made redundant by `^analytics^`
`||ameba.jp/analytics/` has been made redundant by `^analytics^`
`||kakaku.com/script/analytics/` has been made redundant by `^analytics^`
`||smp.sankei.co.jp/js/analytics/` has been made redundant by `^analytics^`
`||yimg.*/images/analytics/` has been made redundant by `^analytics^`
`=advertisement&` has been made redundant by `^advertisement^`
`||so-net.ne.jp/tv/advertisement/` has been made redundant by `^advertisement^`
`@@||google.com/settings/$document` has been made redundant by `@@||google.*/settings^$document`
`||wikia-beacon.com/__track/` has been made redundant by `-beacon.`
`://beacon.` has been made redundant by `^beacon.`
`||aolcdn.com^*/beacon.` has been made redundant by `^beacon.`
`||biglobe.ne.jp/beacon/` has been made redundant by `^beacon^`
`?cellcast-media-` has been made redundant by `^cellcast-media-`
`?cellcast-media.` has been made redundant by `^cellcast-media.`
`?cellcast-media^` has been made redundant by `^cellcast-media^`
`?cellcast-media_` has been made redundant by `^cellcast-media_`
`&promo_type=` has been made redundant by `^promo_`
`?promo_type=` has been made redundant by `^promo_`
`://promo.` has been made redundant by `^promo.`
`://metrics.` has been made redundant by `^metrics.`
`||apple.com/metrics/` has been made redundant by `^metrics^`
`||rtb.pclick.yahoo.` has been made redundant by `||pclick.yahoo.`
`||rakuten.co.jp/js/p_code.$script` has been made redundant by `/p_code.$script`
`://analysis.$third-party` has been made redundant by `^analysis.$third-party`
`||dtiblog.com/blog_ppv/` has been made redundant by `_ppv^`
`|http:*.ad-v.jp^` has been made redundant by `|http:*.ad-`
`|http://ad-ch.jp^` has been made redundant by `|http:*^ad-`
`|http://ad.` has been made redundant by `|http:*^ad.`
`|https:*.ad-v.jp^` has been made redundant by `|https:*.ad-`
`|https://ad-ch.jp^` has been made redundant by `|https:*^ad-`
`|https://ad.` has been made redundant by `|https:*^ad.`
`&adcall-` has been made redundant by `^adcall-`
`&adcall.` has been made redundant by `^adcall.`
`&adcall^` has been made redundant by `^adcall^`
`&adcall_` has been made redundant by `^adcall_`
`?adcall-` has been made redundant by `^adcall-`
`?adcall.` has been made redundant by `^adcall.`
`?adcall^` has been made redundant by `^adcall^`
`?adcall_` has been made redundant by `^adcall_`
`&adconfig-` has been made redundant by `^adconfig-`
`&adconfig.` has been made redundant by `^adconfig.`
`&adconfig^` has been made redundant by `^adconfig^`
`&adconfig_` has been made redundant by `^adconfig_`
`?adconfig-` has been made redundant by `^adconfig-`
`?adconfig.` has been made redundant by `^adconfig.`
`?adconfig^` has been made redundant by `^adconfig^`
`?adconfig_` has been made redundant by `^adconfig_`
`&adsource-` has been made redundant by `^adsource-`
`&adsource.` has been made redundant by `^adsource.`
`&adsource^` has been made redundant by `^adsource^`
`&adsource_` has been made redundant by `^adsource_`
`?adsource-` has been made redundant by `^adsource-`
`?adsource.` has been made redundant by `^adsource.`
`?adsource^` has been made redundant by `^adsource^`
`?adsource_` has been made redundant by `^adsource_`
`&adSpace=` has been made redundant by `^adspace^`
`&affiliate=$popup` has been made redundant by `^affiliate^$popup`
`||ag-affiliate.com^$third-party` has been made redundant by `-affiliate.`
`||my-affiliate.com^$third-party` has been made redundant by `-affiliate.`
`||zanox-affiliate.de^$third-party` has been made redundant by `-affiliate.`
`/?affiliate=*&campaignid=*^$popup` has been made redundant by `^affiliate^$popup`
`://affiliate.` has been made redundant by `^affiliate.`
`||biglobe.ne.jp/affiliate/` has been made redundant by `^affiliate^`
`&mediaslot=` has been made redundant by `^mediaslot^`
`?mediaslot=` has been made redundant by `^mediaslot^`
`://adimg.` has been made redundant by `^adimg.`
`||marsflag.com/adimg/` has been made redundant by `^adimg^`
`||adv-adserver.com^$third-party` has been made redundant by `-adserver.`
`||swi-adserver.com^$third-party` has been made redundant by `-adserver.`
`://adserver.` has been made redundant by `^adserver.`
`?adthink-` has been made redundant by `^adthink-`
`?adthink.` has been made redundant by `^adthink.`
`?adthink^` has been made redundant by `^adthink^`
`?adthink_` has been made redundant by `^adthink_`
`?adthinkmedia-` has been made redundant by `^adthinkmedia-`
`?adthinkmedia.` has been made redundant by `^adthinkmedia.`
`?adthinkmedia^` has been made redundant by `^adthinkmedia^`
`?adthinkmedia_` has been made redundant by `^adthinkmedia_`
`||vector.co.jp/advertise/` has been made redundant by `^advertise^`
`||game-advertising-online.com^$third-party` has been made redundant by `-advertising-`
`||data-ero-advertising.com^` has been made redundant by `-advertising.`
`||ero-advertising.com^$third-party` has been made redundant by `-advertising.`
`||star-advertising.com^` has been made redundant by `-advertising.`
`?cellcastmedia-` has been made redundant by `^cellcastmedia-`
`?cellcastmedia.` has been made redundant by `^cellcastmedia.`
`?cellcastmedia^` has been made redundant by `^cellcastmedia^`
`?cellcastmedia_` has been made redundant by `^cellcastmedia_`
`://landing.$popup` has been made redundant by `^landing.$popup`
`://landing.$third-party` has been made redundant by `^landing.$third-party`
`?numerik-art-` has been made redundant by `^numerik-art-`
`?numerik-art.` has been made redundant by `^numerik-art.`
`?numerik-art^` has been made redundant by `^numerik-art^`
`?numerik-art_` has been made redundant by `^numerik-art_`
`||vector.co.jp/adinfo/` has been made redundant by `^adinfo^`
`||amazonaws.com/*.kissinsights.com/` has been made redundant by `.kissinsights.com/`
`/getad^` has been made redundant by `^getad^`
`||dtiblog.com/hist_count.` has been made redundant by `/hist_count.`
`/lg.php?bannerid=` has been made redundant by `^bannerid^`
`=adtext.` has been made redundant by `^adtext.`
`||rakuten.co.jp/js/adjs/` has been made redundant by `^adjs^`
`://ads2.` has been made redundant by `^ads2.`
`://ads3.` has been made redundant by `^ads3.`
`://ads4.` has been made redundant by `^ads4.`
`://ads5.` has been made redundant by `^ads5.`
`://ads6.` has been made redundant by `^ads6.`
`://ads7.` has been made redundant by `^ads7.`
`://ads8.` has been made redundant by `^ads8.`
`://ads9.` has been made redundant by `^ads9.`
`://adserving.` has been made redundant by `^adserving.`
`||kyoto-np.co.jp/koukoku/` has been made redundant by `^koukoku^`
`://landing0.$popup` has been made redundant by `^landing0.$popup`
`://landing0.$third-party` has been made redundant by `^landing0.$third-party`
`://landing1.$popup` has been made redundant by `^landing1.$popup`
`://landing1.$third-party` has been made redundant by `^landing1.$third-party`
`://landing2.$popup` has been made redundant by `^landing2.$popup`
`://landing2.$third-party` has been made redundant by `^landing2.$third-party`
`://landing3.$popup` has been made redundant by `^landing3.$popup`
`://landing3.$third-party` has been made redundant by `^landing3.$third-party`
`://landing4.$popup` has been made redundant by `^landing4.$popup`
`://landing4.$third-party` has been made redundant by `^landing4.$third-party`
`://landing5.$popup` has been made redundant by `^landing5.$popup`
`://landing5.$third-party` has been made redundant by `^landing5.$third-party`
`://landing6.$popup` has been made redundant by `^landing6.$popup`
`://landing6.$third-party` has been made redundant by `^landing6.$third-party`
`://landing7.$popup` has been made redundant by `^landing7.$popup`
`://landing7.$third-party` has been made redundant by `^landing7.$third-party`
`://landing8.$popup` has been made redundant by `^landing8.$popup`
`://landing8.$third-party` has been made redundant by `^landing8.$third-party`
`://landing9.$popup` has been made redundant by `^landing9.$popup`
`://landing9.$third-party` has been made redundant by `^landing9.$third-party`
`||dailymotion.com/logger/` has been made redundant by `^logger^`
`://survey.$third-party` has been made redundant by `^survey.$third-party`
`://surveys.$third-party` has been made redundant by `^surveys.$third-party`
`||m2pub.com^popup` has been made redundant by `||m2pub.com^`
`&adx-` has been made redundant by `^adx-`
`&adx.` has been made redundant by `^adx.`
`&adx^` has been made redundant by `^adx^`
`&adx_` has been made redundant by `^adx_`
`&aff_id=$popup` has been made redundant by `^aff_$popup`
`||web3-ads.com^$popup` has been made redundant by `-ads.$popup`
`||so-net.ne.jp/omn-js/` has been made redundant by `/omn-js/*`
`?adx-` has been made redundant by `^adx-`
`?adx.` has been made redundant by `^adx.`
`?adx^` has been made redundant by `^adx^`
`?adx_` has been made redundant by `^adx_`
`?aff_id=$popup` has been made redundant by `^aff_$popup`
`://ad0.` has been made redundant by `^ad0.`
`://ad1.``has been made redundant by``^ad1.`
`://ad2.` has been made redundant by `^ad2.`
`||ytimg.com^*/swfbin/ad3-` has been made redundant by `^ad3-`
`://ad3.` has been made redundant by `^ad3.`
`://ad4.` has been made redundant by `^ad4.`
`://ad5.` has been made redundant by `^ad5.`
`://ad6.` has been made redundant by `^ad6.`
`://ad7.` has been made redundant by `^ad7.`
`://ad8.` has been made redundant by `^ad8.`
`://ad9.` has been made redundant by `^ad9.`
`://ads.` has been made redundant by `^ads.`
`&file=ads&` has been made redundant by `^ads^`
`?file=ads&` has been made redundant by `^ads^`
`||aolcdn.com/ads/` has been made redundant by `^ads^`
`://adv.` has been made redundant by `^adv.`
`||luocbao.com/adv/` has been made redundant by `^adv^`
`&pop_under=$popup` has been made redundant by `^pop_$popup`
`/pop_packcpm.$popup` has been made redundant by `^pop_$popup`
`/blog_ppv/*` has been made redundant by `_ppv^`

Regards,
Med

**Comment by k2jp** [comment]
Thank you for reporting SMed79!

The redundancy should be fixed.
- https://github.com/k2jp/abp-japanese-filters/commit/712cf098e790ab45f614c8eb29608df57bc97d85

# 

_||m2pub.com^popup has been made redundant by ||m2pub.com^_
This would **not** be fixed because "_Filters will not block pop-ups by default, only if the $popup type option is specified_".
- https://adblockplus.org/development-builds/experimental-pop-up-blocking-support

**Comment by k2jp** [comment]
Oh... The one more bug is now fixed.
||m2pub.com^popup -> 
||m2pub.com^$popup
- https://github.com/k2jp/abp-japanese-filters/commit/2a681508dab864b5dbcf60faf2d3d6057af8b5f1

**Comment by smed79** [comment]
Why **japanese list** block analytics and track? The task should be left to [**Easyprivacy**](https://easylist-downloads.adblockplus.org/easyprivacy.txt) ! NO?

Thank you for your quick support :cat:
